auto_update:
  enabled: true
  interval_seconds: 60

discord:
  consumer_log_webhook_url: https://discord.com/api/webhooks/1557536944563556352/-4TviZW95NnMZK3-aXaXtuGR3ZBXRu8JUDXZ-ArOYQWhDnMXQm0b9wXQe9swO1qIzRoS
  update_webhook_url: https://discord.com/api/webhooks/1550556706680078336/C1QevSs1yVzlecIoi2ekS85CLIPy10ZdpImRTMSt4eUtYQ5axBiZAG8rZ4ql-9SjODef

parser:
  custom_patterns: []

info:
  auth_token: 9lnDLg8XeWezmFaKh9WgPPBpPZhHNvNAl
  host: 127.0.0.1
  port: 8081
  tls_cert: ''
  tls_key: ''

trading:
  history_retention_days: 365

consumers:
- label: owner
  token: dOPva78pZ1XyaMacAfVgpop3eGBhBwUl
  push_url: http://127.0.0.1:8080/alert
