pipeline_url: http://localhost:8081/alert
poll_interval: 0.5
max_items: 40
auth_token: 9lnDLg8XeWezmFaKh9WgPPBpPZhHNvNA
auto_scroll: true
channels:
- player-alerts
- test-alerts
discord_reopen_seconds: 5
discord_restart_seconds: 30
channel_servers:
  player-alerts: SPX Plays
reader_log_webhook_url: https://discord.com/api/webhooks/1550423714439630868/u05mDtDFe5x9eSvzyqW45SVJ6AEo7HHpu7H1BBOR6AKj7GlQwgpQqSpKtOz2bYDAQ_u2
raw_alert_webhook_url: https://discord.com/api/webhooks/1552880329453346896/FHXDfL34IWT4Ze9OaEJYrOBYJMCn6U_bDMxkBW7H9asL0y7vY8h7dya9g0JLD4e-jw_C
update_webhook_url: https://discord.com/api/webhooks/1550556706680078336/C1QevSs1yVzlecIoi2ekS85CLIPy10ZdpImRTMSt4eUtYQ5axBiZAG8rZ4ql-9SjODef

# defaults made explicit (see config/reader.config.yaml)
auto_start_discord: true
auto_switch_channel: true
